name: Update Weather Prediction

on:
  schedule:
    - cron: "0 0 * * *" # Runs once every day

jobs:
  predict-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run prediction script
        env:
          NIXTLA_API_KEY: ${{ secrets.NIXTLA_API_KEY }}
        run: uv run python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git pull
          git add plot.png
          git commit -m "🔄 Updated forecast graph" || echo "No changes to commit"
          git push
